name: smart_school
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5        
  mqtt_client: ^10.0.0    
  fl_chart: ^0.69.2
  cupertino_icons: ^1.0.8
  animate_do: ^3.3.4
  sleek_circular_slider: ^2.0.1
  permission_handler: ^11.3.1
  flutter_spinkit: ^5.2.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  wifi_iot: ^0.3.19+1
  firebase_database: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
